export const currentSchemeInitialValue = {
  _id: null,
  status: null,
  mass: null,
  price: null,
  deadline: null,
  startingMaterial: null,
  targetCompound: null,
  createdAt: null,
  updatedAt: null,
  stages: [],
};

export const currentStageInitialValue = {
  _id: null,
  _yield: null,
  solvent: null,
  startingMaterial: null,
  methodic: null,
  temp: null,
  time: null,
  product: null,
  testSuccess: false,
  scalingSuccess: false,
  isChanged: false,
  attempts: [
    {
      attemptNumber: 1,
      _id: null,
      _yield: null,
      solvent: null,
      methodic: null,
      temp: null,
      time: null,
      notes: null,
      startingMaterialMass: null,
      productMass: null,
      productPurity: null,
      type: "test",
      isOk: false,
      spectra: [],
      reagents: [
        {
          reagentNumber: 1,
          smiles: null,
          equivalents: null,
          molecularWeight: null,
          mass: null,
        },
        {
          reagentNumber: 2,
          smiles: null,
          equivalents: null,
          molecularWeight: null,
          mass: null,
        },
        {
          reagentNumber: 3,
          smiles: null,
          equivalents: null,
          molecularWeight: null,
          mass: null,
        },
        {
          reagentNumber: 4,
          smiles: null,
          equivalents: null,
          molecularWeight: null,
          mass: null,
        },
      ],
    },
  ],
};

export const setAttemptInitialValue = (attemptnumber: number) => {
  return {
    attemptNumber: attemptnumber,
    _id: null,
    _yield: null,
    solvent: null,
    methodic: null,
    temp: null,
    time: null,
    notes: null,
    startingMaterialMass: null,
    productMass: null,
    productPurity: null,
    type: "test",
    isOk: false,
    spectra: [],
    reagents: [
      {
        reagentNumber: 1,
        smiles: null,
        equivalents: null,
        molecularWeight: null,
        mass: null,
      },
      {
        reagentNumber: 2,
        smiles: null,
        equivalents: null,
        molecularWeight: null,
        mass: null,
      },
      {
        reagentNumber: 3,
        smiles: null,
        equivalents: null,
        molecularWeight: null,
        mass: null,
      },
      {
        reagentNumber: 4,
        smiles: null,
        equivalents: null,
        molecularWeight: null,
        mass: null,
      },
    ],
  };
};
