export const testSchemePreviewDataActive = {
  _id: "64dab5750f9d36f00dacd0b2",
  status: "active",
  mass: 321,
  price: 300,
  deadline: "20.10.2023",
  stagesNumber: 7,
  startingMaterial: "N#CC1=CC=CC=C1",
  targetCompound: "C1(C2=NCCN2)=CC=CC=C1",
  createdAt: "14.08.2023",
  updatedAt: "16.08.2023",
};

export const testSchemePreviewDataSuccess = {
  _id: "64dab5750f9d36f00dacd0b2",
  status: "success",
  mass: 222,
  price: 500,
  deadline: "22.10.2023",
  stagesNumber: 7,
  startingMaterial: "N#CC1=CC=CC=C1",
  targetCompound: "C1(C2=NCCN2)=C",
  createdAt: "23.09.2023",
  updatedAt: "19.10.2023",
};

export const testSchemePreviewDataFail = {
  _id: "64dab5750f9d36f00dacd0b2",
  status: "fail",
  mass: 555,
  price: 600,
  deadline: "15.11.2023",
  stagesNumber: 7,
  startingMaterial: "N#CC1=CC=CC=C1",
  targetCompound: "C1(C2=NCCN2)=CC=CC=C1",
  createdAt: "12.05.2023",
  updatedAt: "07.08.2023",
};

export const testSchemePreviewDataChosen = {
  _id: "64dab5750f9d36f00dacd0b2",
  status: "chosen",
  mass: 234,
  price: 900,
  deadline: "22.12.2023",
  stagesNumber: 7,
  startingMaterial: "N#CC1=CC=CC=C1",
  targetCompound: "C1(C2=NCCN2)=CC=CC=C1",
  createdAt: "15.07.2023",
  updatedAt: "18.09.2023",
};

export const testSchemesPreviewData = [
  testSchemePreviewDataActive,
  testSchemePreviewDataSuccess,
  testSchemePreviewDataSuccess,
  testSchemePreviewDataActive,
  testSchemePreviewDataFail,
  testSchemePreviewDataChosen,
  testSchemePreviewDataFail,
  testSchemePreviewDataFail,
  testSchemePreviewDataActive,
  testSchemePreviewDataActive,
  testSchemePreviewDataSuccess,
  testSchemePreviewDataFail,
  testSchemePreviewDataActive,
  testSchemePreviewDataActive,
  testSchemePreviewDataActive,
  testSchemePreviewDataSuccess,
  testSchemePreviewDataFail,
  testSchemePreviewDataActive,
  testSchemePreviewDataSuccess,
  testSchemePreviewDataActive,
  testSchemePreviewDataFail,
  testSchemePreviewDataFail,
  testSchemePreviewDataChosen,
  testSchemePreviewDataChosen,
  testSchemePreviewDataChosen,
  testSchemePreviewDataChosen,
  testSchemePreviewDataSuccess,
  testSchemePreviewDataActive,
  testSchemePreviewDataChosen,
  testSchemePreviewDataChosen,
];
